//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buzzle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobHistory
    {
        public int JobID { get; set; }
        public string HistoryNote { get; set; }
        public System.DateTime DateInserted { get; set; }
        public int RecordedByUserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Job Job { get; set; }
    }
}
