//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buzzle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPayment
    {
        public int JobID { get; set; }
        public int TransactionID { get; set; }
        public string Notes { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        public virtual Job Job { get; set; }
    }
}
