//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buzzle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyItem
    {
        public int SupplyItemID { get; set; }
        public int SupplyID { get; set; }
        public int PurchaseItemID { get; set; }
        public int PurchasedUnitPrice { get; set; }
        public int PurchasedQuantity { get; set; }
        public Nullable<int> TotalSpent { get; set; }
        public int StockItemTypeID { get; set; }
    
        public virtual PurchaseItem PurchaseItem { get; set; }
        public virtual StockItemType StockItemType { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
